# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  vmImage: windows-latest

steps:
- task: PowerBIActions@5
  inputs:
    PowerBIServiceEndpoint: 'PowerBI_ConnectionPersonal'
    Action: 'Publish'
    WorkspaceName: 'MyDemo_IB'
    PowerBIPath: '/SampleReport.pbix'